version: '3'

services:
  redis:
    image: redis
    ports:
      - "6379:6379"
  postgres:
    user: root
    image: 'postgres:10-alpine'
    environment:
      POSTGRES_PASSWORD: postgres
    command: postgres -c max_wal_size=5120
    volumes:
      - './volumes/postgres:/var/lib/postgresql/data'
    ports:
      - '5432:5432'
  backend:
    build:
      context: ./
      dockerfile: ./backend/Dockerfile
    command: python manage.py runserver 0.0.0.0:8000
    ports:
      - '8000:8000'
    volumes:
      - './backend/app:/src/app'
      - './backend/files:/srv/files'
      - './volumes/media/backend:/srv/media'
    depends_on:
      - postgres
      - redis


volumes:
  postgres: